### ISSUE TITLE
Covid19 day-month argument mixup

### ISSUE THREAD

**Issue by loathwine** [jdegoes/fp-to-the-min#1]
I noticed that Covid19.unsafeLoad/load expects parameters in order _day-month_, but it is called with order _month-day_. This seems to work because there is another mixup in _formFullPath_: expected naming convention is _MM-DD-YYYY_ but called with _DD-MM-YYYY_.

*Edit: Added a pull request with fix.

**Comment by jdegoes** [comment]
Thank you! 🙏
